apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: smtp
  namespace: default
spec:
  type: bindings.smtp
  version: v1
  metadata:
    - name: host
      value: "smtp.mailgun.org"
    - name: port
      value: "587"
    - name: user
      value: ""
    - name: password
      value: ""
    - name: emailFrom
      value: ""