apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: alert-subscription
  namespace: default
spec:
  topic: alerts
  route: /alert
  pubsubname: redis-pubsub
  metadata:
    rawPayload: "true"
